### ISSUE TITLE
set-poc command sets letter assignee to leader assignee

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/api#161] opened 2017-09-05 09:39 UTC
Right now letter boxes created by the set-poc command are automatically assigned to "API User":
 
![setpoc](https://user-images.githubusercontent.com/5891442/30054933-a64ae9d6-91e2-11e7-914c-4008bd79aeba.png)

![api](https://user-images.githubusercontent.com/5891442/30055012-e2976d9c-91e2-11e7-828f-425f13a51e4d.png)

This means I have to manually self-assign letters sent to club leaders created by the set-poc command. It would be great if it automatically assigned me to the letter (because I'm already the leader's assignee).

![assigned](https://user-images.githubusercontent.com/5891442/30055181-73b6f630-91e3-11e7-9712-597af31c5db7.png)

**Comment by paked** [comment] 2017-09-05 21:21
Potential duplicate of #159?

**Comment by MaxWofford** [comment] 2017-09-06 00:23
@paked: Yep. Because both are assigned to you, how about you close the one you don't want. Seems like the main difference is granularity of the task.

**Closed** 2018-12-16 06:09 UTC
Labels: api
